name: Jacoco Coverage Report (develop)

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_URL }}
          POSTGRES_USER: ${{ secrets.DATASOURCE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport -Dspring.profiles.active=ci
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          USER_MAIL: ${{ secrets.USER_MAIL }}
          SPRING_DATASOURCE_URL: ${{ secrets.POSTGRES_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          name: jacoco-report
          fail_ci_if_error: true