name: Jacoco Coverage Report

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          USER_MAIL: ${{ secrets.USER_MAIL }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
          name: jacoco-report
          fail_ci_if_error: true