name: Test PostgreSQL Only

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  
env:
  POSTGRES_DB: ${{ secrets.DB_NAME }}
  POSTGRES_USER: ${{ secrets.DATASOURCE_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432


jobs:
  check-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check DB connection
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql -h localhost -U ${{ env.DATASOURCE_USERNAME }} -d ${{ env.DB_NAME }} -c "SELECT current_database();"
          psql -h localhost -U ${{ env.DATASOURCE_USERNAME }} -d ${{ env.DB_NAME }} -c "SELECT version();"
        env:
          PGPASSWORD: ${{ env.STGRES_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run tests with coverage
        run: |
          ./gradlew clean test \
            --tests "io.github.Toku2001.trackandfieldapp.controller.RegisterUserControllerTest" \
            jacocoTestReport \