name: Test PostgreSQL Only

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  
env:
  POSTGRES_DB: ${{ secrets.DB_NAME }}
  POSTGRES_USER: ${{ secrets.DATASOURCE_USERNAME }}
  POSTGRES_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
  USER_MAIL: ${{ secrets.USER_MAIL }}


jobs:
  check-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check DB connection
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c "SELECT current_database();"
          psql -h localhost -U ${{ env.POSTGRES_USER }} -d ${{ env.POSTGRES_DB }} -c "SELECT version();"
        env:
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run tests with coverage
        run: |
          ./gradlew clean test \
            --tests "io.github.Toku2001.trackandfieldapp.controller.RegisterUserControllerTest" \
            jacocoTestReport \
            -Dspring.profiles.active=ci \
            -DDB_URL=jdbc:postgresql://localhost:5432/${{ env.POSTGRES_DB }} \
            -DPOSTGRES_USER=${{ env.POSTGRES_USER }} \
            -DPOSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} \
            -DJWT_SECRET=${{ env.JWT_SECRET }} \
            -DSENDGRID_KEY=${{ env.SENDGRID_KEY }} \
            -DUSER_MAIL=${{ env.USER_MAIL }}