name: Test PostgreSQL Only

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  
env:
  POSTGRES_DB: trackandfield
  POSTGRES_USER: trackandfield
  POSTGRES_PASSWORD: trackandfield
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
  USER_MAIL: ${{ secrets.USER_MAIL }}

jobs:
  check-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: trackandfield
          POSTGRES_USER: trackandfield
          POSTGRES_PASSWORD: trackandfield
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check DB connection
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql -h localhost -U trackandfield -d trackandfield -c "SELECT current_database();"
          psql -h localhost -U trackandfield -d trackandfield -c "SELECT version();"
        env:
          PGPASSWORD: trackandfield

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run tests and generate coverage report
        run: |
          ./gradlew clean test --tests "io.github.Toku2001.trackandfieldapp.controller.RegisterUserControllerTest"
          ./gradlew jacocoTestReport
        env:
          POSTGRES_DB: trackandfield
          POSTGRES_USER: trackandfield
          POSTGRES_PASSWORD: trackandfield
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          USER_MAIL: ${{ secrets.USER_MAIL }}